// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijssgfvcxnhanluliliw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqc3NnZnZjeG5oYW5sdWxpbGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMjQ5MzgsImV4cCI6MjA1NDkwMDkzOH0.Y3Te5gz5kc6wIL0Advt_7nqO_X3nxe3P3XZOFiFEgA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);